import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  allFilms: [
    {
      id: 0,
      title: "House of Cards",
      genre: "Action",
      slug: "house",
      thumbnail: "http://localhost:8000/thumbnail/house",
      preview: "http://localhost:8000/preview/house",
      duration: "1 hours 57 min",
      ageLimit: "16",
      views: 2199,
      favorite: false,
      desc: "House of Cards is an American political thriller streaming television series created by Beau Willimon. It is based on the 1989 novel of the same name by Michael Dobbs",
    },
    {
      id: 1,
      title: "Mission: Impossible",
      genre: "Action",
      slug: "mission",
      thumbnail: "http://localhost:8000/thumbnail/mission",
      preview: "http://localhost:8000/preview/mission",
      duration: "2 hours 34 min",
      ageLimit: "12",
      views: 30210,
      favorite: false,
      desc: "House of Cards is an American political thriller streaming television series created by Beau Willimon. It is based on the 1989 novel of the same name by Michael Dobbs",
    },
    {
      id: 2,
      title: "Gray Man",
      genre: "Action",
      slug: "grayman",
      thumbnail: "http://localhost:8000/thumbnail/grayman",
      preview: "http://localhost:8000/preview/grayman",
      duration: "1 hours 18 min",
      ageLimit: "12",
      views: 1804,
      favorite: false,
      desc: "House of Cards is an American political thriller streaming television series created by Beau Willimon. It is based on the 1989 novel of the same name by Michael Dobbs",
    },
    {
      id: 3,
      title: "Lupin",
      genre: "Series",
      slug: "lupin",
      thumbnail: "http://localhost:8000/thumbnail/lupin",
      preview: "http://localhost:8000/preview/lupin",
      duration: "40 hours 58 min",
      ageLimit: 7,
      views: 451804,
      favorite: false,
      desc: "House of Cards is an American political thriller streaming television series created by Beau Willimon. It is based on the 1989 novel of the same name by Michael Dobbs",
    },
    {
      id: 4,
      title: "Red Notice",
      genre: "Series",
      slug: "rednotice",
      thumbnail: "http://localhost:8000/thumbnail/rednotice",
      preview: "http://localhost:8000/preview/rednotice",
      duration: "34 hours 58 min",
      ageLimit: "7",
      views: 12804,
      favorite: false,
      desc: "House of Cards is an American political thriller streaming television series created by Beau Willimon. It is based on the 1989 novel of the same name by Michael Dobbs",
    },
    {
      id: 5,
      title: "Wednesday",
      genre: "Series",
      slug: "wednesday",
      thumbnail: "http://localhost:8000/thumbnail/wednesday",
      preview: "http://localhost:8000/preview/wednesday",
      duration: "51 hours 58 min",
      ageLimit: "11",
      views: 1212804,
      favorite: false,
      desc: "House of Cards is an American political thriller streaming television series created by Beau Willimon. It is based on the 1989 novel of the same name by Michael Dobbs",
    },
    {
      id: 6,
      title: "Stranger Things",
      genre: "Series",
      slug: "stranger",
      thumbnail: "http://localhost:8000/thumbnail/stranger",
      preview: "http://localhost:8000/preview/stranger",
      duration: "70 hours 08 min",
      ageLimit: "9",
      views: 4932804,
      favorite: false,
      desc: "House of Cards is an American political thriller streaming television series created by Beau Willimon. It is based on the 1989 novel of the same name by Michael Dobbs",
    },
    {
      id: 7,
      title: "Jumangi",
      genre: "Thriller",
      slug: "jumangi",
      thumbnail: "http://localhost:8000/thumbnail/jumangi",
      preview: "http://localhost:8000/preview/jumangi",
      duration: "1 hours 43 min",
      ageLimit: "6",
      views: 804,
      favorite: false,
      desc: "House of Cards is an American political thriller streaming television series created by Beau Willimon. It is based on the 1989 novel of the same name by Michael Dobbs",
    },
    {
      id: 8,
      title: "2 Guns",
      genre: "Comedy",
      slug: "2guns",
      thumbnail: "http://localhost:8000/thumbnail/2guns",
      preview: "http://localhost:8000/preview/2guns",
      duration: "2 hours 5 min",
      ageLimit: "14",
      views: 324804,
      favorite: false,
      desc: "House of Cards is an American political thriller streaming television series created by Beau Willimon. It is based on the 1989 novel of the same name by Michael Dobbs",
    },
    {
      id: 9,
      title: "Class Onion",
      genre: "Thriller",
      slug: "classonion",
      thumbnail: "http://localhost:8000/thumbnail/classonion",
      preview: "http://localhost:8000/preview/classonion",
      duration: "3 hours 2 min",
      ageLimit: "13",
      views: 23112804,
      favorite: false,
      desc: "House of Cards is an American political thriller streaming television series created by Beau Willimon. It is based on the 1989 novel of the same name by Michael Dobbs",
    },
    {
      id: 10,
      title: "House",
      genre: "rednotice",
      slug: "house",
      thumbnail: "http://localhost:8000/thumbnail/house",
      preview: "http://localhost:8000/preview/house",
      duration: "34 hours 58 min",
      ageLimit: "7",
      views: 12804,
      favorite: false,
      desc: "House of Cards is an American political thriller streaming television series created by Beau Willimon. It is based on the 1989 novel of the same name by Michael Dobbs",
    },
  ],
};

export const filmSlice = createSlice({
  name: "film",
  initialState,
  reducers: {
    addList: (state, action) => {
      let addFilm = action.payload;
      state.allFilms.forEach((e) => {
        if (e.id === addFilm.id) {
          e.favorite = !e.favorite;
        }
      });
    },
  },
});

export const { addList } = filmSlice.actions;

export default filmSlice.reducer;
